exports.binanceCoinName = [
  "0x",
  "Zilliqa",
  "Horizen",
  "Zcash",
  // "YFIUP",
  "yearn-finance-ii",
  // "YFIDOWN",
  "yearn finance",
  "Venus",
  // "XTZUP",
  // "XTZDOWN",
  "Tezos",
  // "XRPUP",
  // "XRPDOWN",
  "XRP",
  "Monero",
  // "XLMUP",
  // "XLMDOWN",
  "Stellar",
  "NEM",
  "Waltonchain",
  "WazirX",
  "Wrapped NXM",
  "Wing",
  "WINk",
  "Waves",
  "Wanchain",
  "VeThor Token",
  "VITE",
  "VeChain",
  "Utrust",
  "Tether",
  "USD Coin",
  "UNIUP",
  "UNIDOWN",
  "Uniswap",
  "Unifi Protocol DAO",
  "UMA",
  "Trust Wallet Token",
  "TrueUSD",
  // "TRXUP",
  // "TRXDOWN",
  "TRON",
  "TrueFi",
  "TROY",
  "Tellor",
  "TomoChain",
  "Alien Worlds",
  "Toko Token",
  "THETA",
  "Theta Fuel",
  "TokenClub",
  // "SXPUP",
  // "SXPDOWN",
  "Swipe",
  // "SUSHIUP",
  // "SUSHIDOWN",
  "SushiSwap",
  "sUSD",
  "SuperFarm",
  "SUN",
  "Stacks",
  "Stratis",
  "Standard Tokenization Protocol",
  "Storj",
  "StormX",
  "Serum",
  "Solana",
  "Synthetix network token",
  "Small Love Potion",
  "SKALE Network",
  "SafePal",
  "Siacoin",
  "The Sandbox",
  "Ravencoin",
  "THORChain",
  "Reserve Rights",
  "Oasis Network",
  "RLC",
  "RSK Infrastructure Framework",
  "Augur",
  "Ren",
  "Reef",
  "RAMP",
  "Qtum",
  "PundiX new",
  "Paris Saint-Germain Fan Token",
  "Marlin",
  "pNetwork",
  "Perpetual Protocol",
  "Perlin",
  "PAX Gold",
  "Paxos Standard",
  "Orchid",
  "Orion Protocol",
  "Ontology",
  "Ontology Gas",
  "Harmony",
  "OMG",
  "MANTRA DAO",
  "Origin Protocol",
  "OG Fan Token",
  "Ocean Protocol",
  "NULS",
  "Pundi X",
  "Numeraire",
  "NKN",
  "Neo",
  "NEAR Protocol",
  "New BitShares",
  "Nano",
  "Metal",
  "Maker",
  "Mithril",
  "Mirror Protocol",
  "IOTA",
  "Hifi Finance",
  "Measurable Data Token",
  "MovieBloc",
  "Polygon",
  "Decentraland",
  "Terra",
  "LTO Network",
  // "LTCUP",
  // "LTCDOWN",
  "Litecoin",
  "Lisk",
  "Loopring",
  "Litentry",
  // "LINKUP",
  // "LINKDOWN",
  "Chainlink",
  "Linear",
  "Kusama",
  "Kyber Network Crystal Legacy",
  "Komodo",
  "Selfkey",
  "Kava",
  "Juventus Fan Token",
  "JUST",
  "IRISnet",
  "IoTeX",
  "IOSToken",
  "Injective Protocol",
  "ICON",
  "Holo",
  "Helium",
  "Hive",
  "Hedera Hashgraph",
  "HARD Protocol",
  "Gifto",
  "The Graph",
  "Pound Sterling",
  "FUNToken",
  "FTX Token",
  "Fantom",
  "Ampleforth Governance Token",
  "Flamingo",
  "Stafi",
  "Firo",
  "FIO Protocol",
  // "FILUP",
  // "FILDOWN",
  "Filecoin",
  "Fetch",
  "Euro",
  // "ETHUP",
  // "ETHDOWN",
  "Ethereum",
  "Ethereum Classic",
  "Ellipsis",
  // "EOSUP",
  // "EOSDOWN",
  "EOS",
  "Enjin Coin",
  "Elrond",
  "Dusk Network",
  "Drep new",
  // "DOTUP",
  // "DOTDOWN",
  "Polkadot",
  "Dogecoin",
  "DODO",
  "Dock",
  "district0x",
  "DIA",
  "DigiByte",
  "Dent",
  "Dego Finance",
  "Decred",
  "Streamr",
  "Dash",
  "Civic",
  "Cortex",
  "Cartesi",
  "CertiK",
  "Curve DAO Token",
  "COTI",
  "Contentos",
  "Compound",
  "Cocos-BCX",
  "Nervos Network",
  "Chiliz",
  "Chromia",
  "Conflux Network",
  "Celer Network",
  "Celo",
  "PancakeSwap",
  "bZx Protocol",
  "Binance USD",
  "Burger Swap",
  "BitTorrent",
  "BitShares",
  "Bitcoin Gold",
  // "BTCUP",
  // "Bitcoin Standard Hashrate Token",
  // "BTCDOWN",
  "Bitcoin",
  "Bancor",
  // "BNBUP",
  // "BNBDOWN",
  "Binance Coin",
  "Bluzelle",
  "Bella Protocol",
  "Beam",
  "Bitcoin Cash",
  "Basic Attention Token",
  "FC Barcelona Fan Token",
  "Band Protocol",
  "Balancer",
  "BakeryToken",
  "Badger DAO",
  "Axie Infinity",
  "Avalanche",
  "Travala",
  "Auto",
  "Audius",
  "Australian Dollar",
  "Cosmos",
  "Atletico De Madrid Fan Token",
  "AS Roma Fan Token",
  "ARPA Chain",
  "Ardor",
  "Aragon",
  "Ankr",
  "Alpha Finance Lab",
  "MyNeighborAlice",
  "Algorand",
  "Akropolis",
  "Aion",
  // "ADAUP",
  // "ADADOWN",
  "Cardano",
  "AC Milan Fan Token",
  // "AAVEUP",
  // "AAVEDOWN",
  "Aave",
  "1inch",
];
