exports.coinCategories = [
  "Tourism",
  "Retail",
  "Media",
  "Sharing Economy",
  "Entertainment",
  "Loyalty",
  "Marketing",
  "Content Creation",
  "Energy",
  "binance smart chain",
  "Yield farming",
  "Storage",
  "Analytics",
  "Video",
  "Logistics",
  "Fan token",
  "Filesharing",
  "Distributed Computing",
  "Winklevoss Capital",
  "Scaling",
  "DAO",
  "Framework Ventures",
  "Smart Contracts",
  "Asset management",
  "Cosmos Ecosystem",
  "Kinetic Capital",
  "Huobi Capital",
  "Masternodes",
  "IoT",
  "Decentralized exchange",
  "Cybersecurity",
  "Privacy",
  "Binance Launchpool",
  "Research",
  "ParaFi capital",
  "lending-borowing",
  "Yield Aggregator",
  "Paradigm XZY Screener",
  "Health",
  "DeFi",
  "Memes",
  "collectibles-nfts",
  "Centralized exchange",
  "Oracles",
  "Derivatives",
  "Synthetics",
  "Gaming",
  "Polkadot Ecosystem",
  "Binance Launchpad",
  "Yearn Partnerships",
  "ai-big-data",
  "Hospitality",
  "Identity",
  "Insurance",
  "Interoperability",
  "Music",
  "AMM",
  "DeFiance Capital",
  "DAO Maker",
  "Avalanche Ecosystem",
  "Wrapped Tokens",
  "Metaverse",
  "Sports",
  "Gambling",
  "Stablecoin",
  "Solana Ecosystem",
  "platform",
  "pow",
  "mineable",
  "services",
  "payments",
];
