exports.coinCategories = [
  "Tourism",
  "Retail",
  "Events",
  "Media",
  "E-commerce",
  "Social Money",
  "Sharing Economy",
  "DeFi Index",
  "Entertainment",
  "Loyalty",
  "Marketing",
  "Content Creation",
  "Energy",
  "DragonFly Capital Portfolio",
  "binance smart chain",
  "Yield farming",
  "Fenbushi Capital Portfolio",
  "1Confirmation Portfolio",
  "communications-social-media",
  "Storage",
  "Analytics",
  "Galaxy Digital Portfolio",
  "Trustswap Launchpad",
  "Video",
  "Logistics",
  "Rebase",
  "Options",
  "Fan token",
  "Blockchain Capital Portfolio",
  "ETH 2 0 Staking",
  "Filesharing",
  "Distributed Computing",
  "Winklevoss Capital",
  "Scaling",
  "Fabric Ventures Portfolio",
  "LedgerPrime Portfolio",
  "DAO",
  "Framework Ventures",
  "Smart Contracts",
  "Asset management",
  "Jobs",
  "Cosmos Ecosystem",
  "Kinetic Capital",
  "Huobi Capital",
  "BoostVC Portfolio",
  "Masternodes",
  "USV Portfolio",
  "IoT",
  "DCG Portfolio",
  "Polychain Capital Portfolio",
  "Decentralized exchange",
  "Cybersecurity",
  "Privacy",
  "Binance Launchpool",
  "Research",
  "ParaFi capital",
  "Pantera Capital Portfolio",
  "lending-borowing",
  "Alameda Research Portfolio",
  "Yield Aggregator",
  "Binance Labs Portfolio",
  "Paradigm XZY Screener",
  "Hashkey Capital Portfolio",
  "Health",
  "DeFi",
  "Memes",
  "collectibles-nfts",
  "Multicoin Capital Portfolio",
  "Placeholder Ventures Portfolio",
  "Centralized exchange",
  "Three Arrows Capital Portfolio",
  "DuckSTARTER",
  "CMS Holdings Portfolio",
  "Oracles",
  "A16Z Portfolio",
  "Derivatives",
  "electric-capital-portfolio",
  "Synthetics",
  "Gaming",
  "Polkadot Ecosystem",
  "Binance Launchpad",
  "Yearn Partnerships",
  "ai-big-data",
  "Hospitality",
  "Identity",
  "Exnetwork Capital Portfolio",
  "Insurance",
  "Interoperability",
  "Coinbase Ventures Portfolio",
  "Music",
  "AMM",
  "Coinfund Portfolio",
  "DeFiance Capital",
  "DAO Maker",
  "Avalanche Ecosystem",
  "Launchpad",
  "Aave Tokens",
  "Wrapped Tokens",
  "Metaverse",
  "VR AR",
  "Polkastarter",
  "Sports",
  "Gambling",
  "Stablecoin",
  "Solana Ecosystem",
  "Tokenized Stock",
  "Transport",
  "Seigniorage",
  "Poolz Finance",
  "Real Estate",
  "Education",
  "Hacken Foundation",
  "platform",
  "pow",
  "mineable",
  "services",
  "payments",
];
