exports.coinPortfolios = [
  "DragonFly Capital Portfolio",
  "Fenbushi Capital Portfolio",
  "1Confirmation Portfolio",
  "Galaxy Digital Portfolio",
  "Blockchain Capital Portfolio",
  "Fabric Ventures Portfolio",
  "LedgerPrime Portfolio",
  "BoostVC Portfolio",
  "USV Portfolio",
  "DCG Portfolio",
  "Polychain Capital Portfolio",
  "Pantera Capital Portfolio",
  "Alameda Research Portfolio",
  "Binance Labs Portfolio",
  "Hashkey Capital Portfolio",
  "Multicoin Capital Portfolio",
  "Placeholder Ventures Portfolio",
  "Three Arrows Capital Portfolio",
  "CMS Holdings Portfolio",
  "A16Z Portfolio",
  "electric-capital-portfolio",
  "Exnetwork Capital Portfolio",
  "Coinbase Ventures Portfolio",
  "Coinfund Portfolio",
];
