exports.upbitCoinName = [
  "Dogecoin",
  "Ethereum Classic",
  "XRP",
  "Bitcoin Cash",
  "BitTorrent",
  "Ethereum",
  "EOS",
  "Bitcoin",
  "Bitcoin Gold",
  "Chainlink",
  "Waves",
  "Neo",
  "VeChain",
  "Litecoin",
  "Dawn Protocol",
  "Qtum",
  "SIRIN LABS Token",
  "Bitcoin Cash ABC",
  "TRON",
  "Stellar",
  "MediBloc",
  "Theta Fuel",
  "Tezos",
  "OMG",
  "Siacoin",
  "Bitcoin SV",
  "Cardano",
  "Polkadot",
  "Pundi X",
  "Chiliz",
  "Swipe",
  "Standard Tokenization Protocol",
  "Decentraland",
  "Status",
  "Ontology",
  "THETA",
  "NEM",
  "Strike",
  // "Spendcoin",
  "Serum",
  "Metadium",
  "MiLk alliance",
  "Gas",
  "Pundi X nem",
  "Stacks",
  "Metal",
  "Stratis",
  "StormX",
  "Maro",
  "The Sandbox",
  "Cosmos",
  "PayProtocol",
  "MVL",
  "Augur",
  "Hifi Finance",
  "Crypto com Coin",
  "Axie Infinity",
  "Ark",
  "MovieBloc",
  "Carry",
  "SOMESING",
  "Lisk",
  "Lambda",
  "Ankr",
  "Cobak Token",
  "Everipedia",
  "Steem",
  "Basic Attention Token",
  "PIXEL",
  "Enjin Coin",
  "Tokamak Network",
  "dKargo",
  "Observer",
  "Quiztok",
  "Hedera Hashgraph",
  "Zilliqa",
  "Einsteinium",
  "Groestlcoin",
  "JUST",
  "BORA",
  "0x",
  "Adx Net",
  "Orbs",
  "Refereum",
  "Civic",
  "Ontology Gas",
  "IOSToken",
  "Kava",
  "Thunder Token",
  "Endor Protocol",
  "FirmaChain",
  "Hive",
  "Ardor",
  "Alpha Quark Token",
  "Kyber Network Crystal Legacy",
  "Moss Coin",
  "12Ships",
  "Humanscape",
  "Gifto",
  "Storj",
  "Komodo",
  "HUNT",
  "Aergo",
  "Sentinel Protocol",
  "Golem",
  "Polymath-network",
  "ICON",
  "DMarket",
  "SOLVE",
  "PlayDapp",
  "IOTA",
  "QuarkChain",
  "Steem Dollars",
  "Loom Network",
  "WAX",
  "Ignis",
  "Power Ledger",
  "aelf",
  "OST",
  "library-credit",
];
